server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 2701
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  exchange:
    serie:
      name: my-serie-exchange
  queue:
    serie:
      name: my-serie-queue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true